apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-repair-api
  labels:
    app: it-repair-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: it-repair-api
  template:
    metadata:
      labels:
        app: it-repair-api
    spec:
      containers:
      - name: it-repair-api
        # ใช้ image ที่ build จาก local
        image: yaichakkarin/it-repair-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: FORCE_UPDATE
          value: "placeholder"
        # !!! แก้ IP ฐานข้อมูลด้านล่าง !!!
        - name: DB_HOST
          value: "34.158.49.62" 
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "SuperSecretPassword123!"
        - name: DB_NAME
          value: "it_repair"