apiVersion: v1
kind: Service
metadata:
  name: it-repair-api-svc
spec:
  type: LoadBalancer
  selector:
    app: it-repair-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http